### ISSUE TITLE
Some airports have incorrect ident, iata and local code

### ISSUE THREAD

**Issue by Bonob0b** [datasets/airport-codes#11]
Some airports have incorrect ident, iata and local code : 

To identify them ,  search for 'E+' in the file (probably due to an excel import and automatic conversion.). The original file from  http://ourairports.com/data/ is correct though.

The airports are : 
0.00E+00,small_airport,Corydon Airport,"-93.24130249, 40.75450134",1020,NA,US,US-IA,Corydon,0.00E+00,,0.00E+00
1.00E+02,small_airport,Terlingua Ranch Airport,"29.45019913, -103.3990021",3769,NA,US,US-TX,Alpine,1.00E+02,,1.00E+02
1.00E+04,small_airport,Palo Duro Airport,"35.14199829, -101.8379974",3639,NA,US,US-TX,Amarillo,1.00E+04,,1.00E+04
1.00E+06,small_airport,Elkins Field,"34.45780182, -78.61830139",93,NA,US,US-NC,Clarkton,1.00E+06,,2NR2
1.00E+07,small_airport,Buffalo Airport,"35.06499863, -101.8789978",3640,NA,US,US-TX,Amarillo,1.00E+07,,1.00E+07
1.00E+08,small_airport,Moores Airport,"44.38759995, -75.06629944",814,NA,US,US-NY,Degrasse,1.00E+08,,1.00E+08
1.00E+09,small_airport,Maples Field,"35.06529999, -101.9609985",3677,NA,US,US-TX,Canyon,1.00E+09,,1.00E+09

**Comment by Mikanebu** [comment]
@Bonob0b Thanks for creating an issue for this.

**Comment by zelima** [comment]
@Mikanebu can you actually fix this and indeed add a script to `/scripts` folder that concatenates those two columns

**Comment by Mikanebu** [comment]
@zelima I will add a script and update csv with the latest changes

**Comment by Mikanebu** [comment]
@Bonob0b @zelima Fixed, Added scripts, updated data itself.

**Comment by Mikanebu** [comment]
FIXED,  `ident`, `iata` and `local code` are all correct
