### ISSUE TITLE
Invalid geopoint type

### ISSUE THREAD

**Issue by Mikanebu** [datasets/airport-codes#14]
`Invalid geopoint type latitude should be between -90 and 90, found: -151.6959991`

it's not a valid geopoint according to the specs: 
> Geopoint type is a string of the pattern "lon, lat"

In `airport-codes.csv` geopoint column has a "lat, lon" format which is in reverse order. So a latitude with a value -151.6959991 is invalid.
See the following issue in `tableschema-js` 
https://github.com/frictionlessdata/tableschema-js/issues/72

**Comment by rufuspollock** [comment]
@Mikanebu why do we have to have lat in +/- 90?

**Comment by Mikanebu** [comment]
@rufuspollock because it is the range for latitude [-90;+90]

**Comment by rufuspollock** [comment]
@Mikanebu is this now fixed?

**Comment by Mikanebu** [comment]
@rufuspollock it is fixed, but pipeline showed the same error, we were going to report to Adam about two core data packages `airport-codes` and `smdg-master-terminal-facilities-list`. Something wrong with `geopoint` type

**Comment by rufuspollock** [comment]
@Mikanebu can you open an issue on assembler about this then please - and close this issue in favour of that.

**Comment by Mikanebu** [comment]
FIXED
