### ISSUE TITLE
[Feature Request] Other IACA Codes

### ISSUE THREAD

**Issue by matgrioni** [datasets/airport-codes#18]
It would be nice to also have the IACA codes for country and cities other than just airports. I am just going to extract this data from an API instead, but I think it would be a good addition for this. I can PR the information later when I get it extracted.

**Comment by rufuspollock** [comment]
@matgrioni that would be great - please add as a PR when you have it 😄

**Comment by rufuspollock** [comment]
@matgrioni any update here?

**Comment by matgrioni** [comment]
I should have the info soon. I had it before, but my laptop was recently stolen and I'm a bit busy with finals, so in the next few weeks I should have it again.
