### ISSUE TITLE
Missing ICAO code: OTHH (instead named "QA-0001")

### ISSUE THREAD

**Issue by dtonhofer** [datasets/airport-codes#21]
That is Hamad International Airport 
https://en.wikipedia.org/wiki/Hamad_International_Airport
Well, it _is_ in there but with:

ident = QA-0001 (this seems to be a placeholder; it does not look like an ICAO code at all; one finds it in use around the web, but I would they these sites are using this very dataset)
gps_code = OTHH (this is the ICAO code)
iata_code = DOH (correct IATA code)

**Comment by Mikanebu** [comment]
FIXED.
