### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by vurso** [datasets/airport-codes#4]

**Comment by rgrp** [comment]
Which link?

**Comment by rufuspollock** [comment]
@AcckiyGerman when you close issues can you **please** add a note as to why as per our standard guidelines.

**Comment by AcckiyGerman** [comment]
WONTFIX:
The issue description is vague, all the links listed in readme are alive.

**Comment by vurso** [comment]
Sorry I must have been drunk at the time

**Comment by AcckiyGerman** [comment]
:+1: no problem
