### ISSUE TITLE
Geopoint type field has an invalid format.

### ISSUE THREAD

**Issue by Mikanebu** [datasets/airport-codes#5]
Geopoint type supports in the followings formats:
1. default. A string of the pattern “lon, lat”. 
2. array. An array of exactly two items
3. object. A JSON object with exactly two keys, lat and lon.

Please, correct to the right format.

**Comment by rufuspollock** [comment]
@Mikanebu can you do a pull request for this fix to the data and we can merge it.

**Comment by Mikanebu** [comment]
@rufuspollock  which solution would be better? 
* Merge 2 columns("latitude" and 'longitute") into one("coordinates")
* Fix metada - change "type":"geopoint" to "string"
