### ISSUE TITLE
Update schema to be more restrictive

### ISSUE THREAD

**Issue by danfowler** [datasets/airport-codes#9]
See: #11 (original: https://discuss.okfn.org/t/error-in-file-http-data-okfn-org-data-core-airport-codes-data/5734/2)

> No problem in the source http://ourairports.com/data/, but in http://data.okfn.org/data/core/airport-codes#data, some airports have a wrong identifier and iata code and local code.

> I can propose a corrected file, but how can I do that ?
> please help.

> Where is the problem ?
> Easy to identify, search for 'E+' in the file (probably due to an excel import and automatic conversion...) :
> 0.00E+00,small_airport,Corydon Airport,"-93.24130249, 40.75450134",1020,NA,US,US-IA,Corydon,0.00E+00,,0.00E+00
> 1.00E+02,small_airport,Terlingua Ranch Airport,"29.45019913, -103.3990021",3769,NA,US,US-TX,Alpine,1.00E+02,,1.00E+02
> 1.00E+04,small_airport,Palo Duro Airport,"35.14199829, -101.8379974",3639,NA,US,US-TX,Amarillo,1.00E+04,,1.00E+04
> 1.00E+06,small_airport,Elkins Field,"34.45780182, -78.61830139",93,NA,US,US-NC,Clarkton,1.00E+06,,2NR2
> 1.00E+07,small_airport,Buffalo Airport,"35.06499863, -101.8789978",3640,NA,US,US-TX,Amarillo,1.00E+07,,1.00E+07
> 1.00E+08,small_airport,Moores Airport,"44.38759995, -75.06629944",814,NA,US,US-NY,Degrasse,1.00E+08,,1.00E+08
> 1.00E+09,small_airport,Maples Field,"35.06529999, -101.9609985",3677,NA,US,US-TX,Canyon,1.00E+09,,1.00E+09

**Comment by Mikanebu** [comment]
@danfowler Thank you for proposing this solution. First, we have to fix data in issue #11.

**Comment by Mikanebu** [comment]
FIXED, this is fixed in https://github.com/datasets/airport-codes/issues/11
